[package]
name = 'choose'
slug = 'choose'
version = ''
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = ['hyperupcall/bash-args@e5466e6c3998790ebd99768cf0f910e161b84a95']
binDirs = ['pkg/bin']
