[package]
type = 'bash'
name = 'choose'
slug = 'choose'
version = '0.3.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'System for choosing default applications, programs, and utilities'

[run]
dependencies = ['https://github.com/hyperupcall/bash-args@v0.10.0', 'https://github.com/hyperupcall/bash-core.git@v0.6.0']
sourceDirs = ['pkg/src']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
errfail = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
