[package]
type = 'bash'
name = 'choose'
slug = 'choose'
version = '0.2.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'System for choosing default applications, programs, and utilities'

[run]
dependencies = ['https://github.com/hyperupcall/bash-args.git@v0.10.0']
sourceDirs = ['pkg/src']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
