[package]
name = 'choose'
slug = 'choose'
version = ''
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = ['https://github.com/hyperupcall/bash-args.git@v0.9.0']
sourceDirs = ['pkg/lib']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
